version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app

  db:
    build: ./mongo_rs
    restart: always
    environment:
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_REPLICA_HOST: db
      # MONGODB_REPLICA_SET_MODE: primary
      # MONGODB_REPLICA_SET_KEY: 123456
      MONGODB_DATABASE: nest
    volumes:
      - ./mongodb_data:/bitnami/mongodb

volumes:
  mongodb_data:
    driver: local

networks:
  my-network:
    external: true
